# one time php script run without compose:
# docker run --rm -v $(pwd):/app/ php:8.2-cli php /app/phpinfo.php

services:
    nginx:
        container_name: ca-nginx
        image: nginx:1.23-alpine
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/app
        ports:
            - 80:80

    # interactive:
    # docker exec --interactive --tty ca-php /bin/sh
    # docker exec -it ca-php /bin/sh
    # 
    # one time:
    # docker exec ca-php php /app/info.php 
    php:
        container_name: ca-php
        image: php:8.2-fpm-alpine
        working_dir: /app
        volumes:
            - ./src:/app
        # tty: true